name: Schedule Test
on:
  schedule:
    - cron: '*/5 * * * *'  # Every 2 minutes for testing
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "✅ Schedule Test - Running at $(date)"
          echo "This proves automatic scheduling works!"
